theme: jekyll-theme-architect
title: Is government necessary?
authors: "Marquis Kurt and Reggie Nillo"

download:
  source:           "https://github.com/alicerunsonfedora/playgrounds-necessity-government/releases/latest.zip"
  dist:             "https://github.com/alicerunsonfedora/playgrounds-necessity-government/releases/latest.zip"