title: Is Government Necessary?
authors: "Marquis Kurt and Reggie Nillo"

download:
  source:           "https://github.com/alicerunsonfedora/playgrounds-necessity-government/releases/latest.zip"
  dist:             "https://github.com/alicerunsonfedora/playgrounds-necessity-government/releases/latest.zip"
